version: '3.8'

services:
  # PHP Service container
  laravel_app:
    platform: linux/amd64
    build:
      args:
        user: laravel_user
        uid: 1000
      context: .
      dockerfile: ./Dockerfile
    image: laravel_app_image
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      -   ./:/var/www
    networks:
      - laravel_app_network
  #nginx service
  laravel_webserver:
    platform: linux/amd64
    image: nginx:alpine
    container_name: laravel_webserver_container
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      -   laravel_app
    volumes:
      -   ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d
    networks:
      - laravel_app_network
networks:
  laravel_app_network:
    driver: bridge
